apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "triton-inference.fullname" . }}-models
  labels:
    {{- include "triton-inference.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.modelRepository.storageClass }}
  resources:
    requests:
      storage: {{ .Values.modelRepository.pvcSize }}
